require("dotenv").config();
const { WebClient } = require("@slack/web-api");
const cron = require("node-cron");
const messages = require("./messages");
const express = require("express");
const { MongoClient } = require("mongodb");
const path = require("path");

const client = new WebClient(process.env.SLACK_TOKEN);
const app = express();
const port = process.env.PORT || 3000;
app.use(express.json());

// ==========================================
// 1. MONGODB CONNECTION
// ==========================================
const mongoClient = new MongoClient(process.env.MONGO_URI);
let db;

mongoClient.connect()
  .then(client => {
      db = client.db("CommunityBot");
          console.log("✅ Successfully connected to MongoDB Cloud!");
            })
              .catch(err => console.error("❌ MongoDB connection error:", err));


              // ==========================================
              // 2. HELPER FUNCTIONS
              // ==========================================
              const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));


              // ==========================================
              // 3. MAIN BROADCAST LOGIC
              // ==========================================
              async function sendDailyMessageToAll() {
                if (!db) {
                    console.error("Database not connected yet. Cannot broadcast.");
                        return;
                          }

                            try {
                                // A. GET CURRENT DAY FROM MONGODB (Bulletproof State)
                                    const stateColl = db.collection("bot_state");
                                        let state = await stateColl.findOne({ _id: "campaign_state" });
                                            
                                                // If no state exists yet, start at Day 0
                                                    if (!state) {
                                                          state = { _id: "campaign_state", currentDay: 0 };
                                                                await stateColl.insertOne(state);
                                                                    }

                                                                        let day = state.currentDay;

                                                                            if (day >= messages.length) {
                                                                                  console.log("All 30 days of messages have been sent!");
                                                                                        return;
                                                                                            }

                                                                                                console.log(`Starting broadcast for Day ${day + 1}...`);
                                                                                                    const messageText = messages[day];

                                                                                                        // B. POST TO GENERAL CHANNEL
                                                                                                            try {
                                                                                                                  if (process.env.CHANNEL_ID) {
                                                                                                                          await client.chat.postMessage({
                                                                                                                                    channel: process.env.CHANNEL_ID,
                                                                                                                                              text: messageText
                                                                                                                                                      });
                                                                                                                                                              console.log("✅ Successfully posted to the main channel!");
                                                                                                                                                                    } else {
                                                                                                                                                                            console.log("⚠️ No CHANNEL_ID found in .env, skipping general channel.");
                                                                                                                                                                                  }
                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                            console.error("❌ Failed to post to main channel:", err.message);
                                                                                                                                                                                                }

                                                                                                                                                                                                    // C. FETCH ALL USERS (Paginated)
                                                                                                                                                                                                        console.log("Fetching complete user list for DMs...");
                                                                                                                                                                                                            let users = [];
                                                                                                                                                                                                                let nextCursor;

                                                                                                                                                                                                                    do {
                                                                                                                                                                                                                          const response = await client.users.list({ cursor: nextCursor, limit: 1000 });
                                                                                                                                                                                                                                const activeHumans = response.members.filter(
                                                                                                                                                                                                                                        (user) => !user.deleted && !user.is_bot && user.id !== "USLACKBOT"
                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                    users = users.concat(activeHumans);
                                                                                                                                                                                                                                                          nextCursor = response.response_metadata?.next_cursor;
                                                                                                                                                                                                                                                              } while (nextCursor);

                                                                                                                                                                                                                                                                  console.log(`Found ${users.length} active users. Starting DM broadcast...`);

                                                                                                                                                                                                                                                                      // D. SEND DMs WITH RATE LIMITING
                                                                                                                                                                                                                                                                          for (const user of users) {
                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                        await client.chat.postMessage({
                                                                                                                                                                                                                                                                                                  channel: user.id, 
                                                                                                                                                                                                                                                                                                            text: messageText
                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                            console.log(`Sent DM to ${user.profile.real_name || user.name}`);
                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                          console.error(`Failed to send DM to ${user.name}:`, err.message);
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            await sleep(1500); // 1.5 second delay
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                    console.log(`🎉 Successfully finished broadcasting Day ${day + 1}`);
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                            // E. UPDATE DAY IN MONGODB FOR TOMORROW
                                                                                                                                                                                                                                                                                                                                                                                await stateColl.updateOne(
                                                                                                                                                                                                                                                                                                                                                                                      { _id: "campaign_state" },
                                                                                                                                                                                                                                                                                                                                                                                            { $set: { currentDay: day + 1 } }
                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                      console.error("Fatal error during broadcast:", error);
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                        // 4. CRON SCHEDULER
                                                                                                                                                                                                                                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                        cron.schedule("0 9 * * *", () => {
                                                                                                                                                                                                                                                                                                                                                                                                          console.log("Cron job triggered at 9:00 AM. Starting broadcast...");
                                                                                                                                                                                                                                                                                                                                                                                                            sendDailyMessageToAll();
                                                                                                                                                                                                                                                                                                                                                                                                            }, {
                                                                                                                                                                                                                                                                                                                                                                                                              timezone: "Africa/Lagos"
                                                                                                                                                                                                                                                                                                                                                                                                              });


                                                                                                                                                                                                                                                                                                                                                                                                              // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                              // 5. EXPRESS ENDPOINTS (Events & Admin)
                                                                                                                                                                                                                                                                                                                                                                                                              // ==========================================

                                                                                                                                                                                                                                                                                                                                                                                                              // Health Check
                                                                                                                                                                                                                                                                                                                                                                                                              app.get("/", (req, res) => res.send("Mastering Backend Bot is live and connected to DB!"));

                                                                                                                                                                                                                                                                                                                                                                                                              // Serve Admin HTML Page
                                                                                                                                                                                                                                                                                                                                                                                                              app.get("/admin", (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                res.sendFile(path.join(__dirname, "admin.html"));
                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                // Admin API to fetch logs
                                                                                                                                                                                                                                                                                                                                                                                                                app.get("/api/logs", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                  const { secret } = req.query;
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                      if (secret !== process.env.ADMIN_SECRET) {
                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(401).send("Unauthorized");
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                              if (!db) return res.status(500).send("Database not connected");

                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                    const logs = await db.collection("engagement_logs")
                                                                                                                                                                                                                                                                                                                                                                                                                                                             .find()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .sort({ timestamp: -1 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .toArray();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   res.json(logs);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         res.status(500).send(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Listen for Slack Replies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           app.post("/slack/events", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const { type, challenge, event } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (type === "url_verification") return res.status(200).send(challenge);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (type === "event_callback" && event.type === "message") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (event.bot_id) return res.status(200).send("Ignored bot message");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.log(`📩 NEW REPLY FROM USER ${event.user}: ${event.text}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (db) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await db.collection("engagement_logs").insertOne({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     userId: event.user,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               channel: event.channel,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         message: event.text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   timestamp: new Date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.error("❌ Failed to save to database:", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       res.status(200).send("Event received");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       app.listen(port, () => console.log(`Web server listening on port ${port}`));
                                                                                                                                                                                                                                                                    